- os: osx
matrix:
  include:
  - osx_image: xcode6.4
  - osx_image: xcode7.3
  - osx_image: xcode8gm
  - osx_image: xcode8.1
  - osx_image: xcode8.2
  - osx_image: xcode8.3
  - osx_image: xcode6.4
    env: FROM_SOURCE=--source
  - osx_image: xcode7.3
    env: FROM_SOURCE=--source
  - osx_image: xcode8gm
    env: FROM_SOURCE=--source
  - osx_image: xcode8.1
    env: FROM_SOURCE=--source
  - osx_image: xcode8.2
    env: FROM_SOURCE=--source
  - osx_image: xcode8.3
    env: FROM_SOURCE=--source

script:
  - ./install.macports "$FROM_SOURCE"
