language: objective-c

matrix:
  include:
  - osx_image: xcode7.3
  - osx_image: xcode8gm
  - osx_image: xcode8.1
  - osx_image: xcode8.2
  - osx_image: xcode8.3
  - osx_image: xcode7.3
    env: PRE=$HOME/opt
  - osx_image: xcode8gm
    env: PRE=$HOME/opt
  - osx_image: xcode8.1
    env: PRE=$HOME/opt
  - osx_image: xcode8.2
    env: PRE=$HOME/opt
  - osx_image: xcode8.3
    env: PRE=$HOME/opt

script:
# this is required for curl to work correctly:
  - export COLUMNS=80
  - if test -z "$PRE" ; then PRE=/opt/local ; fi
  - ./install.macports --prefix="$PRE"
  - PATH="$PRE/bin:$PATH"
  - which port
# install a small port for test:
  - sudo port -N install xdrfile
  - sudo port -N uninstall xdrfile
  - ./config.macports --prefix="$PRE" test_portfiles
# install a small local port for test:
  - sudo port -N install xdrfile1
