language: objective-c

matrix:
  include:
  - osx_image: xcode7.3
    env: FROM_SOURCE=no
  - osx_image: xcode8gm
    env: FROM_SOURCE=no
  - osx_image: xcode8.1
    env: FROM_SOURCE=no
  - osx_image: xcode8.2
    env: FROM_SOURCE=no
  - osx_image: xcode8.3
    env: FROM_SOURCE=no
  - osx_image: xcode7.3
    env: FROM_SOURCE=--source
  - osx_image: xcode8gm
    env: FROM_SOURCE=--source
  - osx_image: xcode8.1
    env: FROM_SOURCE=--source
  - osx_image: xcode8.2
    env: FROM_SOURCE=--source
  - osx_image: xcode8.3
    env: FROM_SOURCE=--source

script:
  - ./install.macports "$FROM_SOURCE"
