language: objective-c

matrix:
  include:
  - osx_image: xcode7.3
    env: OPT=--binary
  - osx_image: xcode8gm
    env: OPT=--binary
  - osx_image: xcode8.1
    env: OPT=--binary
  - osx_image: xcode8.2
    env: OPT=--binary
  - osx_image: xcode8.3
    env: OPT=--binary
  - osx_image: xcode7.3
    env: OPT=--source
  - osx_image: xcode8gm
    env: OPT=--source
  - osx_image: xcode8.1
    env: OPT=--source
  - osx_image: xcode8.2
    env: OPT=--source
  - osx_image: xcode8.3
    env: OPT=--source
  - osx_image: xcode7.3
    env: OPT=--prefix=/opt/local-test
  - osx_image: xcode8gm
    env: OPT=--prefix=/opt/local-test
  - osx_image: xcode8.1
    env: OPT=--prefix=/opt/local-test
  - osx_image: xcode8.2
    env: OPT=--prefix=/opt/local-test
  - osx_image: xcode8.3
    env: OPT=--prefix=/opt/local-test

script:
  - ./install.macports "$OPT"
# install a small port for test:
  - PATH="/opt/local/bin:$PATH"
  - PATH="/opt/local-test/bin:$PATH"
  - sudo port -N install xdrfile
  - sudo port -N uninstall xdrfile
  - ./config.macports test_portfiles
  - sudo port -N install xdrfile1
