language: objective-c

matrix:
  include:
  - osx_image: xcode7.3
    env: OPT=--binary
  - osx_image: xcode8gm
    env: OPT=--binary
  - osx_image: xcode8.1
    env: OPT=--binary
  - osx_image: xcode8.2
    env: OPT=--binary
  - osx_image: xcode8.3
    env: OPT=--binary
  - osx_image: xcode7.3
    env: OPT=--source
  - osx_image: xcode8gm
    env: OPT=--source
  - osx_image: xcode8.1
    env: OPT=--source
  - osx_image: xcode8.2
    env: OPT=--source
  - osx_image: xcode8.3
    env: OPT=--source

script:
  - ./install.macports "$OPT"
