
osx_image:
  - xcode6.4
  - xcode7.3
  - xcode8gm
  - xcode8.1
  - xcode8.2
  - xcode8.3
  - xcode6.4

env:
  - FROM_SOURCE=no
  - FROM_SOURCE=--source

script:
  - ./install.macports "$FROM_SOURCE"
